#!/bin/bash

# A func to download, build ...
build_aur () {
    old_dir=`pwd`
    # Prep with a build-user:
    useradd -m -G wheel builder
    sed -i 's/# %wheel ALL=(ALL) NO/%wheel ALL=(ALL) NO/' /etc/sudoers

    cd /tmp
    rm -rf $1 $1.tar.gz
    wget "https://aur.archlinux.org/cgit/aur.git/snapshot/$1.tar.gz"
    tar xvzf "$1.tar.gz"

    cd $1
    build_dir=$(pwd)
    chown -R builder.builder /tmp/$1
    su - builder -c "(cd ${build_dir}; makepkg -s --noconfirm)"

    if [[ $3 -eq "yes" ]]; then
        pacman -U --noconfirm *.xz
    fi  

    sh -c "mv *.xz ${old_dir}/$2/$1.pkg.tar.xz"

    cd ${old_dir}
    userdel builder
    rm -rf /home/builder
    rm -rf /tmp/$1
    rm /tmp/$1.tar.gz
}

echo "Starting to sync upstream changes to mirror."
mkdir -p ${work_dir}/${arch}/airootfs/srv/http/archlinux/arch_offline/os/x86_64
rm -rf /tmp/sync /tmp/local

pacman --noconfirm --dbpath /tmp/ -Syu -w --cachedir ${work_dir}/${arch}/airootfs/srv/http/archlinux/arch_offline/os/${arch} base base-devel git python python-systemd nano sudo iptables dhclient dnsmasq openssh sshfs openssl openvpn gcc openvpn powerdns postgresql sqlite go c-ares http-parser libuv nodejs-less mariadb memcached bzip2 glib2 libev lua51 ragel zlib >/dev/null
build_aur "gogs-git" "${work_dir}/${arch}/airootfs/srv/http/archlinux/arch_offline/os/${arch}"
build_aur "lighttpd2-git" "${work_dir}/${arch}/airootfs/srv/http/archlinux/arch_offline/os/${arch}" "yes"

sh -c "repo-add --new ${work_dir}/${arch}/airootfs/srv/http/archlinux/arch_offline/os/${arch}/arch_offline.db.tar.gz ${work_dir}/${arch}/airootfs/srv/http/archlinux/arch_offline/os/${arch}/*.pkg.tar.xz" >/dev/null 2>&1
chown -R www-data.www-data ${work_dir}/${arch}/airootfs/srv/http/archlinux

echo "Done syncing offline mirror."
